### PR TITLE
Logo!

### PR DESCRIPTION
**Pull request by Cute-Ducky**
I've added a logo and edited the readme a little bit!

### CODE REVIEW

**Comment by 9glenda** [comment]
It breaks my local branch. I'll have to look into merging it.

**Comment by 9glenda** [comment]
image

**Comment by 9glenda** [comment]
Also the PR is 3 commits behind.

**Comment by 9glenda** [comment]
Also this 6 lines could easily be changed in 1 commit maybe I should sqash them.

**Comment by Cute-Ducky** [comment]
> image

because its in light mode idk what to do about it do you know any?

**Pull request closed without merging**
